"""empty message

Revision ID: 3fdc5d3c6114
Revises: 73ce6a6e4782
Create Date: 2019-12-08 23:45:09.156281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdc5d3c6114'
down_revision = '73ce6a6e4782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('howMany', sa.Integer(), nullable=True))
    op.add_column('basket', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket', 'total')
    op.drop_column('basket', 'howMany')
    # ### end Alembic commands ###
