"""empty message

Revision ID: 79ea074ed2b2
Revises: 3fdc5d3c6114
Create Date: 2019-12-08 23:50:25.589163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ea074ed2b2'
down_revision = '3fdc5d3c6114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('total', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
